name: Build site and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Application
      - name: Build application
        run: npm run build

      # Deploy to Github Pages
      - id: deploy
        name: Deploy to Github Pages
        uses: fcodelabs/react-deploy-github-pages-action@v1.0.0
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
